[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zehranaveedt", email = "162749372+zehranaveedt@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
chatbot = "chatbot:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
